### PR TITLE
added word-play task

### PR DESCRIPTION
**Pull request by akoolarni**
Issue: #120 
@maintainers,
I have added word-play task.
Please merge this PR.

### CODE REVIEW

**Comment by akoolarni** [comment]
Please merge the PR maintainers.

**Comment by shashank-lol** [comment]
This is a competitive task and will be merged after the deadline ends, i.e. 11:59 PM

**Comment by akoolarni** [comment]
Sure

**Comment by shashank-lol** [comment]
The design wasn't justifying the word

**Comment by akoolarni** [comment]
What?

**Comment by akoolarni** [comment]
How come ?

**Comment by akoolarni** [comment]
Doesn't makes sense at all the reason u r giving brother

**Comment by shashank-lol** [comment]
See, there were better designs than yours.

**Comment by akoolarni** [comment]
Then keep those designs with you only.
Doesn't bothers me

**Comment by akoolarni** [comment]
L

**Pull request closed without merging**
