### PR TITLE
added pen tool task1

### PR DESCRIPTION
**Pull request by akoolarni**
Issue: #66 
@maintainers, 
I have revised my drawing and added a much much better version than my previous drawing, which got rejected.
Please merge this PR now.
Thanx

### CODE REVIEW

**Comment by shashank-lol** [comment]
Hi, you have really improved but I am sorry, I can't merge it as this issue allowed only one PR.

**Comment by akoolarni** [comment]
Please merge it na, it would be really helpful for me. I worked really hard

**Comment by shashank-lol** [comment]
I am sorry, the rules are same for everyone. I have rejected a lot of PRs due to this rule.

**Comment by akoolarni** [comment]
Ok np.
Could you please review my Wordplay task

**Comment by akoolarni** [comment]
I did it today's itself, after issue was raised

**Pull request closed without merging**
